### ISSUE TITLE
NODE_ENV=production; Cannot read properties of undefined (reading '$scopedSlots')

### ISSUE THREAD

**Issue by jakedowns** [inertiajs/inertia#1203]
### Versions:

- `@inertiajs/inertia` version: 0.10.1
- `@inertiajs/inertia-vue` version: 0.7.2
- `vue` 2.6.14

### Describe the problem:

when executing a prod compile, and running the compiled code within a production environment,
the client side app fails to boot. 

![image](https://user-images.githubusercontent.com/1683122/175125129-2e3f1f4e-7e59-46b0-9f7e-efc0824f09be.png)

the error thrown indicates that something is happening during the mounting of inertia-head

i'm having trouble diagnosing what in my <inertia-head> element would be breaking things.
i found a similar issue on the nuxt repo (my app does not use nuxt) https://github.com/nuxt/nuxt.js/issues/6185
but i'm not using v-html in any head element, nor do i have any script tags within my vue root, nor my inerita-head

my inertia-head:
```js
<Head :title="$page.props?.metadata?.title ?? ''">
    <meta v-for="(key,value) in $page.props?.metadata ?? {}"
          :key="key"
          :head-key="key"
          :name="key"
          :content="value" />

</Head>
```

error
```
vue.esm.js:1906 TypeError: Cannot read properties of undefined (reading '$scopedSlots')
    at vue.esm.js:4133:27
    at prepatch (vue.esm.js:3153:5)
    at E (vue.esm.js:6363:7)
    at vue.esm.js:6248:9
    at E (vue.esm.js:6374:29)
    at Xi.nodeOps [as __patch__] (vue.esm.js:6537:9)
    at t._update (vue.esm.js:3972:19)
    at a.r (vue.esm.js:4090:10)
    at wn.get (vue.esm.js:4504:25)
    at wn.run (vue.esm.js:4579:22)
```

### Steps to reproduce:

this is going to take me a whole day to create a minimum reproducible test case that i can host online and share, so any insights on what to look for in lieu of doing that would be much appreciated

**Comment by jakedowns** [comment]
this ended up being a mismatch between my server-side compiled code and my client-side compiled code.
my server was running out of disk space and the yarn install was failing, meaning that the server-side code fell behind what the client was executing
