### ISSUE TITLE
Cannot convert Symbol value to String error in Head component when using slot

### ISSUE THREAD

**Issue by wooddotdev** [inertiajs/inertia#1552]
### Version:

- `@inertiajs/vue3` version: 1.0.6

### Describe the problem:

When using the Head component with a `<slot />` following error is received

```
TypeError: Cannot convert a Symbol value to a string
    at Proxy.renderTagStart (head.ts:57:23)
    at Proxy.renderTag (head.ts:72:23)
    at head.ts:91:31
    at Array.map (<anonymous>)
    at Proxy.renderNodes (head.ts:91:12)
    at Proxy.render (head.ts:97:31)
    at renderComponentRoot (runtime-core.esm-bundler.js:816:16)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5764:26)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at instance.update (runtime-core.esm-bundler.js:5814:51)
```

### Steps to reproduce:
1. Add Head component to a page
2. Wait for hot reload / reload page
3. Check console.

Have reproduced on fresh Laravel 10 / Vue 3 / Inertia 1.0.6 install.

**Comment by valh1996** [comment]
+1 I just encountered the problem, it broke my custom Head component in production... :(

I'm willing to help with a fix if someone can point me in the right direction cc @reinink ?

**Comment by valh1996** [comment]
> i think this PR will fix the problem #1509 and i think it was this change that created the problem [vuejs/core@34ad609](https://github.com/vuejs/core/commit/34ad609bd75b5644e7c54d84b163297c51652ab6) @valh1996

Great, thanks! Now we just have to hope that @reinink reviews the PR and deploy a release ASAP 🙏🏻

**Comment by reinink** [comment]
Yup, hoping to get this out this week! 🤞

**Comment by cjholowatyj** [comment]
+1 same issue. I love discovering that solutions are already in the works when an error pops up in my dev environment! Kudos @reinink!

**Comment by tchartron** [comment]
Encountered this also when updating Vue to 3.3.2 lately, thanks a lot @reinink 👍🏼

**Comment by reinink** [comment]
Hey folks, this has been fixed (thanks to @craigrileyuk) and released in `v1.0.7`:

https://github.com/inertiajs/inertia/releases/tag/v1.0.7

Thanks for reporting! 🙏
