### ISSUE TITLE
Links not working sometimes - href toString() undefined

### ISSUE THREAD

**Issue by prattcmp** [inertiajs/inertia#1663]
### Version:

- `@inertiajs/vue3` version: 1.0.0

### Describe the problem:

We are frequently (not always) getting the following error when trying to click on Inertia links:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toString')
    at v (url.ts:6:23)
    at router.ts:385:29
```

We think it happens when a page becomes stale.

### Steps to reproduce:

We haven't figured out how to reproduce this bug consistently. It appears to occur after the page has been stale for a while.

I believe this is the same bug as (they minified their code so the function names are different): https://github.com/inertiajs/inertia/issues/1191

**Comment by ovatsugbp** [comment]
I'm having the same issue everytime I try to redirect to my home page

**Comment by jordin-marshall** [comment]
Im right there with you all =/

**Comment by adnanerlansyah403** [comment]
Please upppp, I have the same issue here 😭

**Comment by a21ns1g4ts** [comment]
@driesvints After some investigation and testing, I'm inclined to believe it's not related to Inertia. The issue might be connected to the domain code, where some errors could be hidden by an afterResponse dispatch.

**Comment by pascalbaljet** [comment]
I've investigated this a bit and I think this could only happen when the backend response is malformed. If you take a look at a [typical Inertia response](https://inertiajs.com/the-protocol#inertia-responses), you'll see that the JSON response has a `url` key, which should be the Page URL.

Feel free to open a new issue if this is still a problem with v2, but please add an example so we can easily reproduce it.
