### ISSUE TITLE
Server Side Rendering createServer is not a function  React

### ISSUE THREAD

**Issue by KonstantinIV** [inertiajs/inertia#1673]
### Version:

- `@inertiajs/react` version: 1.0.11

### Describe the problem:

Topic: Server side rendering

Running the command `php artisan inertia:start-ssr ` 
Ends with error createServer is not a function

 ```
webpack-internal:///./node_modules/@inertiajs/server/lib/index.js:38
  (0, _http.createServer)(async (request, response) => {
                         
TypeError: (0 , _http.createServer) is not a function
    at _default (webpack-internal:///./node_modules/@inertiajs/server/lib/index.js:38:26)
    at eval (webpack-internal:///./resources/js/ssr.js:13:62)
    at ./resources/js/ssr.js (/development/artWebsite/public/js/ssr.js:272:1)
    at __webpack_require__ (/development/artWebsite/public/js/ssr.js:1543:42)
    at /development/artWebsite/public/js/ssr.js:1619:37
    at Object.<anonymous> (/development/artWebsite/public/js/ssr.js:1621:12)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)

**Node.js v19.8.1**

``` 

### Steps to reproduce:
Tried absolutely everything, removing all modules and reinstalling them didnt help.

ssr.js
```
import { createInertiaApp } from '@inertiajs/react';
import { createRoot } from 'react-dom/client';
import createServer from '@inertiajs/server';
import ReactDOMServer from 'react-dom/server';
import React from 'react';

    
createServer(page =>   


  createInertiaApp({    
    page,     
    render: ReactDOMServer.renderToString,
    resolve: name => require(`./components/pages/${name}/${name}.js`),
    setup({ el, App, props }) {
      createRoot(el).render(<App {...props} />)
    },  }),
)  
```
package.json
```
{
    "private": true,
    "name": "Art portfolio website",
    "version": "1.0.1",
    "description": "Art portfolio website",
    "scripts": {
        "dev": "npm run development",
        "development": "mix",
        "watch": "mix watch",
        "watch-poll": "mix watch -- --watch-options-poll=1000",
        "hot": "mix watch --hot",
        "prod": "npm run production",
        "production": "mix --production"
    },
    "devDependencies": {
        "@babel/preset-react": "^7.18.6",
        "@popperjs/core": "^2.10.2",
        "axios": "^0.21",
        "laravel-mix": "^6.0.6",
        "lodash": "^4.17.19",
        "postcss": "^8.1.14",
        "react": "^18.2.0",
        "react-dom": "^18.2.0",
        "resolve-url-loader": "^5.0.0"
    },
    "dependencies": {
        "@inertiajs/progress": "^0.2.7",
        "@inertiajs/react": "^1.0.11",
        "@inertiajs/server": "^0.1.0",
        "node": "^20.6.0",
        "sass": "^1.66.1",
        "sass-loader": "^13.3.2",
        "stream-http": "^3.2.0"
    }
}
```

webpack.mix.js
```
const mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */


mix.js(['resources/js/app.js'], 'public/js/app.js')
    .js(['resources/js/ssr.js'], 'public/js/ssr.js')

    .sass('resources/sass/app.scss', 'public/css')
    .sourceMaps();


    
    mix.webpackConfig({
        resolve: {
            fallback: {
                "http": require.resolve("stream-http"),
            },
        },
        stats: {
             children: true
        }
    });
```
laravel config inertia.php
```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Server Side Rendering
    |--------------------------------------------------------------------------
    |
    | These options configures if and how Inertia uses Server Side Rendering
    | to pre-render the initial visits made to your application's pages.
    |
    | Do note that enabling these options will NOT automatically make SSR work,
    | as a separate rendering service needs to be available. To learn more,
    | please visit https://inertiajs.com/server-side-rendering
    |
    */

    'ssr' => [

        'enabled' => true,

        'url' => 'http://127.0.0.1:13714/render',

    ],

    /*
    |--------------------------------------------------------------------------
    | Testing
    |--------------------------------------------------------------------------
    |
    | The values described here are used to locate Inertia components on the
    | filesystem. For instance, when using `assertInertia`, the assertion
    | attempts to locate the component as a file relative to any of the
    | paths AND with any of the extensions specified here.
    |
    */

    'testing' => [

        'ensure_pages_exist' => true,

        'page_paths' => [

            resource_path('js/Pages'),

        ],

        'page_extensions' => [

            'js',
            'jsx',
            'svelte',
            'ts',
            'tsx',
            'vue',

        ],

    ],

];
```
IMPORTANT NOTE 

http-stream module is used as replacement for node default http module. Defined in webpack.mix.js.

**Comment by ramonmalcolm10** [comment]
Try running the production build before starting the server

**Comment by KonstantinIV** [comment]
> Try running the production build before starting the server

Tried before, tried again to double check. Did not work.

Production build is just minified version of the development build. So it should not solve the problem anyway.

**Comment by craigrileyuk** [comment]
You’re importing createServer from @inertiajs/server, not @inertiajs/react/server

**Comment by KonstantinIV** [comment]
> You’re importing createServer from @inertiajs/server, not @inertiajs/react/server

At first I did import from  @inertiajs/react/server but I got similar error "create server is not a function" so i tried to switch to @inertiajs/server, not indentical but same type of error.


Tried your solution again to double check, did not work. Here is the error. Will keep the import from @inertiajs/react/server.
```
webpack-internal:///./node_modules/@inertiajs/core/dist/server.esm.js:7
var g=t=>new Promise((o,n)=>{let r="";t.on("data",e=>r+=e),t.on("end",()=>o(r)),t.on("error",e=>n(e))}),d=(t,o)=>{let n=o||13714,r={"/health":async()=>({status:"OK",timestamp:Date.now()}),"/shutdown":()=>process__WEBPACK_IMPORTED_MODULE_1__.exit(),"/render":async e=>t(JSON.parse(await g(e))),"/404":async()=>({status:"NOT_FOUND",timestamp:Date.now()})};(0,http__WEBPACK_IMPORTED_MODULE_0__.createServer)(async(e,a)=>{let i=r[e.url]||r["/404"];try{a.writeHead(200,{"Content-Type":"application/json",Server:"Inertia.js SSR"}),a.write(JSON.stringify(await i(e)))}catch(p){console.error(p)}a.end()}).listen(n,()=>console.log("Inertia SSR server started.")),console.log(`Starting SSR server on port ${n}...`)};
                                                                                                                                                                                                                                                                                                                                                                                                                    ^

TypeError: (0 , http__WEBPACK_IMPORTED_MODULE_0__.createServer) is not a function
    at d (webpack-internal:///./node_modules/@inertiajs/core/dist/server.esm.js:7:405)
    at eval (webpack-internal:///./resources/js/ssr.js:12:68)
    at ./resources/js/ssr.js (/development/artWebsite/public/js/ssr.js:261:1)
    at __webpack_require__ (/development/artWebsite/public/js/ssr.js:1640:42)
    at /development/artWebsite/public/js/ssr.js:1716:37
    at Object.<anonymous> (/development/artWebsite/public/js/ssr.js:1718:12)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
Node.js v19.8.1
```

**Comment by ramonmalcolm10** [comment]
These library are included in `@inertiajs/react` by default `@inertiajs/progress ` and `@inertiajs/server`. I would start by removing those first and foremost

**Comment by KonstantinIV** [comment]
> These packages are included in `@inertiajs/react` by default `@inertiajs/progress ` and `@inertiajs/server`. I would start by removing those first and foremost

Did not work

**Comment by KonstantinIV** [comment]
Update
I ditched webpack and went migrated to vite.

Using vite to build files the SSR sarted working.
Not satisfying solution to the problem since i wanted to know what triggers it but oh well.
