### ISSUE TITLE
usePage must be used within the Inertia component in SSR

### ISSUE THREAD

**Issue by MohammadAbdorrahmani** [inertiajs/inertia#1678]
### Version:

- `@inertiajs/react` version: 1.0

I use Inertia SSR in laravel and then run  php artisan inertia:start-ssr :

```
Starting SSR server on port 13714...
Inertia SSR server started.
Error: usePage must be used within the Inertia component
    at exports.usePage (D:\**\***\***\node_modules\@inertiajs\inertia-react\dist\index.js:1:8285)                                                                                              
    at Home (file:///D:/**/**/***/bootstrap/ssr/assets/Home-21516cff.mjs:25:20)                                                                                                               
    at renderWithHooks (D:\**\**\**\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:5662:16)                                                                          
    at renderIndeterminateComponent (D:\**\**\**\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:5735:15)                                                             
    at renderElement (D:\**\**\**\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:5950:7)                                                                             
    at renderNodeDestructiveImpl (D:\***\**\**\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6108:11)                                                                
    at renderNodeDestructive (D:\***\**\**\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6080:14)                                                                    
    at renderContextProvider (D:\**\**\**\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:5924:3)                                                                     
    at renderElement (D:\**\***\**\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6021:11)                                                                            
    at renderNodeDestructiveImpl (D:\**\**\**\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6108:11)                                                                

```
Based on the document, I went forward.
and in Web Page console:

- https://legacy.reactjs.org/docs/error-decoder.html/?invariant=130&args%5B%5D=undefined&args%5B%5D=

How to fix that? 
thanks

**Comment by craigrileyuk** [comment]
Any chance of a reproduction or the code in the file `Home (file:///D:/**/**/***/bootstrap/ssr/assets/Home-21516cff.mjs:25:20)` that seems to be causing the problem?

**Comment by MohammadAbdorrahmani** [comment]
I deleted all the files in ssr directory and did not get the result, it gives the same error again.

**Comment by craigrileyuk** [comment]
You’re using two completely different versions of the intertia React package. You’ve got @inertiajs/inertia-react in some places and @inertiajs/react in others. 

You should only be using @inertiajs/react

**Comment by MohammadAbdorrahmani** [comment]
oops. I don't know how it got like this!

Thanks

**Comment by craigrileyuk** [comment]
> Why does the inertia team maintain two different react repos?

They don’t. One was a legacy package from the inertia repo that was published to NPM. 

The name was changed with v1 release.

**Comment by VIKIVIKA** [comment]
I am getting the similar error, i am using storybook which uses individual components and these components cannot be an Inertia component, these components are indirectly using few hooks that have usePage defined.

I am still getting the above error, i have only one type of import **@inertiajs/react** in my overall application.
