### ISSUE TITLE
Playground vue3 cannot build

### ISSUE THREAD

**Issue by sicaboy** [inertiajs/inertia#1693]
### Version:

- version: latest master

### Describe the problem:

Cannot build frontend.

### Steps to reproduce:

- `git clone git@github.com:inertiajs/inertia.git`
- `cd inertia/playgrounds/vue3`
- `nvm use 16`
- `npm i`
- `npm run dev`

Tried both node 14 and node 16

Throw bunch of errors, one example:
```

✘ [ERROR] Failed to resolve entry for package "@inertiajs/vue3". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]

    ../../node_modules/vite/node_modules/esbuild/lib/main.js:1360:21:
      1360 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///Users/slj/work/inertia/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23382:11)
    at resolvePackageEntry (file:///Users/slj/work/inertia/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23379:5)
    at tryNodeResolve (file:///Users/slj/work/inertia/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23113:20)
    at Context.resolveId (file:///Users/slj/work/inertia/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:22874:28)
    at Object.resolveId (file:///Users/slj/work/inertia/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42847:46)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (file:///Users/slj/work/inertia/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:43145:26)
    at async file:///Users/slj/work/inertia/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:43322:34
    at async requestCallbacks.on-resolve (/Users/slj/work/inertia/node_modules/vite/node_modules/esbuild/lib/main.js:1360:22)
    at async handleRequest (/Users/slj/work/inertia/node_modules/vite/node_modules/esbuild/lib/main.js:723:13)

  This error came from the "onResolve" callback registered here:

    ../../node_modules/vite/node_modules/esbuild/lib/main.js:1279:20:
      1279 │       let promise = setup({
           ╵                     ^

    at setup (file:///Users/slj/work/inertia/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:43312:19)
    at handlePlugins (/Users/slj/work/inertia/node_modules/vite/node_modules/esbuild/lib/main.js:1279:21)
    at buildOrContextImpl (/Users/slj/work/inertia/node_modules/vite/node_modules/esbuild/lib/main.js:968:5)
    at Object.buildOrContext (/Users/slj/work/inertia/node_modules/vite/node_modules/esbuild/lib/main.js:776:5)
    at /Users/slj/work/inertia/node_modules/vite/node_modules/esbuild/lib/main.js:2172:68
    at new Promise (<anonymous>)
    at Object.context (/Users/slj/work/inertia/node_modules/vite/node_modules/esbuild/lib/main.js:2172:27)
    at Object.context (/Users/slj/work/inertia/node_modules/vite/node_modules/esbuild/lib/main.js:2012:58)
    at prepareEsbuildScanner (file:///Users/slj/work/inertia/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:43097:26)

  The plugin "vite:dep-scan" was triggered by this import

    script:/Users/slj/work/inertia/playgrounds/vue3/resources/js/Pages/User.vue?id=1:6:7:
      6 │ import '@inertiajs/vue3'
        ╵        ~~~~~~~~~~~~~~~~~


✘ [ERROR] Failed to resolve entry for package "@inertiajs/vue3". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]

    ../../node_modules/vite/node_modules/esbuild/lib/main.js:1360:21:
      1360 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///Users/slj/work/inertia/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23382:11)
    at resolvePackageEntry (file:///Users/slj/work/inertia/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23379:5)
    at tryNodeResolve (file:///Users/slj/work/inertia/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23113:20)
    at Context.resolveId (file:///Users/slj/work/inertia/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:22874:28)
    at Object.resolveId (file:///Users/slj/work/inertia/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42847:46)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (file:///Users/slj/work/inertia/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:43145:26)
    at async file:///Users/slj/work/inertia/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:43322:34
    at async requestCallbacks.on-resolve (/Users/slj/work/inertia/node_modules/vite/node_modules/esbuild/lib/main.js:1360:22)
    at async handleRequest (/Users/slj/work/inertia/node_modules/vite/node_modules/esbuild/lib/main.js:723:13)

  This error came from the "onResolve" callback registered here:

    ../../node_modules/vite/node_modules/esbuild/lib/main.js:1279:20:
      1279 │       let promise = setup({
           ╵                     ^

    at setup (file:///Users/slj/work/inertia/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:43312:19)
    at handlePlugins (/Users/slj/work/inertia/node_modules/vite/node_modules/esbuild/lib/main.js:1279:21)
    at buildOrContextImpl (/Users/slj/work/inertia/node_modules/vite/node_modules/esbuild/lib/main.js:968:5)
    at Object.buildOrContext (/Users/slj/work/inertia/node_modules/vite/node_modules/esbuild/lib/main.js:776:5)
    at /Users/slj/work/inertia/node_modules/vite/node_modules/esbuild/lib/main.js:2172:68
    at new Promise (<anonymous>)
    at Object.context (/Users/slj/work/inertia/node_modules/vite/node_modules/esbuild/lib/main.js:2172:27)
    at Object.context (/Users/slj/work/inertia/node_modules/vite/node_modules/esbuild/lib/main.js:2012:58)
    at prepareEsbuildScanner (file:///Users/slj/work/inertia/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:43097:26)

  The plugin "vite:dep-scan" was triggered by this import

    script:/Users/slj/work/inertia/playgrounds/vue3/resources/js/Components/Layout.vue?id=0:2:30:
      2 │ import { Link, usePage } from '@inertiajs/vue3'
        ╵                               ~~~~~~~~~~~~~~~~~


    at failureErrorWithLog (/Users/slj/work/inertia/node_modules/vite/node_modules/esbuild/lib/main.js:1636:15)
    at /Users/slj/work/inertia/node_modules/vite/node_modules/esbuild/lib/main.js:1048:25
    at runOnEndCallbacks (/Users/slj/work/inertia/node_modules/vite/node_modules/esbuild/lib/main.js:1471:45)
    at buildResponseToResult (/Users/slj/work/inertia/node_modules/vite/node_modules/esbuild/lib/main.js:1046:7)
    at /Users/slj/work/inertia/node_modules/vite/node_modules/esbuild/lib/main.js:1058:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (/Users/slj/work/inertia/node_modules/vite/node_modules/esbuild/lib/main.js:1057:54)
    at handleRequest (/Users/slj/work/inertia/node_modules/vite/node_modules/esbuild/lib/main.js:723:19)
    at handleIncomingPacket (/Users/slj/work/inertia/node_modules/vite/node_modules/esbuild/lib/main.js:745:7)
    at Socket.readFromStdout (/Users/slj/work/inertia/node_modules/vite/node_modules/esbuild/lib/main.js:673:7)
```

**Comment by jessarcher** [comment]
You must first build the `core` and `vue3` packages (in the `packages` directory).

You can automatically run the build script for all packages and playgrounds with the following command, making sure to install the npm dependencies at the workspace (top) level:

```sh
git clone git@github.com:inertiajs/inertia.git
cd inertia
npm install
npm run build --workspaces --if-present
```

**Comment by sicaboy** [comment]
Thanks @jessarcher it works.
