### ISSUE TITLE
Inertia Server side rendering gives error regarding ReCaptcha

### ISSUE THREAD

**Issue by KonstantinIV** [inertiajs/inertia#1708]
### Version:

- `@inertiajs/react` version: 1.0.11

### Describe the problem:
Importing captcha like this gives error when someone visits the contact page where the recaptcha is used
!IMPORTANT NOTE : The recaptcha itself works completely fine, the SSR jsut doesnt like the way i import the ReCaptcha i guess
 
ContactForm.js
```
import ReCAPTCHA from 'react-google-recaptcha';


other code...
 <ReCAPTCHA
        sitekey={siteKey}
        onChange={handleCaptchaChange}
        name='sendersCaptcha'
      />
```

The error
```
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at ContactForm (file:///var/www/html/artWebsite/bootstrap/ssr/assets/contactForm-17048d75.js:5:3)
    at div
    at div
    at Layout (file:///var/www/html/artWebsite/bootstrap/ssr/assets/layout-ddfc5362.js:71:19)
    at Contact (file:///var/www/html/artWebsite/bootstrap/ssr/assets/contact-01512f3d.js:11:88)
    at M (file:///var/www/html/artWebsite/node_modules/@inertiajs/react/dist/index.esm.js:1:489)
    at div
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at renderElement (/var/www/html/artWebsite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6047:9)
    at renderNodeDestructiveImpl (/var/www/html/artWebsite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)
    at renderNodeDestructive (/var/www/html/artWebsite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
    at renderNode (/var/www/html/artWebsite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6263:12)
    at renderChildrenArray (/var/www/html/artWebsite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6215:7)
    at renderNodeDestructiveImpl (/var/www/html/artWebsite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6145:7)
    at renderNodeDestructive (/var/www/html/artWebsite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
    at renderNode (/var/www/html/artWebsite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6263:12)
    at renderHostElement (/var/www/html/artWebsite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5646:3)
    at renderElement (/var/www/html/artWebsite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5956:5)
```

### Steps to reproduce:
Gives error above
```
import ReCAPTCHA from 'react-google-recaptcha';
```

I tried imprting with curly braces which fixes the issue but then the recaptcha component is not displayed on page

```
import { ReCAPTCHA } from 'react-google-recaptcha';
```

**Comment by craigrileyuk** [comment]
Most captchas work by injecting JavaScript into the user's browser page which tracks their behaviour and then creates a risk profile.

This is impossible in the server-side context and will likely break if code execution is attempted.

If a component is not SSR-compatible, I suggest only attempting to render it when you've confirmed your in a browser context. I don't use React much myself, but something like:

```js
const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);

    // Additional client-side logic can be placed here

    return () => {
      // Cleanup logic when the component unmounts
    };
  }, []); // The empty dependency array ensures the effect runs once after the initial render
 ```

**Comment by reinink** [comment]
Yup, exactly @craigrileyuk!

There is nothing special about the Inertia SSR server — it really just defers to the Vue/React/Svelte SSR rendering engines, so whatever you do in your app must be compatible with what your framework supports in SSR mode 👍
