### ISSUE TITLE
SSR | TypeError: Cannot read properties of undefined (reading 'getSSRProps')

### ISSUE THREAD

**Issue by iambryansanders** [inertiajs/inertia#1850]
### Version:

- `@inertiajs/vue3` version: 1.0.15

### Describe the problem:

I am following the SSR instructions outlined here: [https://inertiajs.com/server-side-rendering](https://inertiajs.com/server-side-rendering) and am getting this error when I run `php artisan inertia:start-ssr` and then visit a page served by `php artisan serve`.

True error: `TypeError: Cannot read properties of undefined (reading 'getSSRProps')
    at ssrGetDirectiveProps (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:477:40)
    at _sfc_ssrRender$9 (bootstrap/ssr/ssr.js:109:16)
    at renderComponentSubTree (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:695:9)
    at renderComponentVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:641:12)
    at ssrRenderComponent (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:84:10)
    at file:///Users/bryansanders/Documents/JustChurchJobs/Repos/LandingPages/bootstrap/ssr/ssr.js:949:20
    at renderFnWithContext (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:815:13)
    at ssrRenderSlotInner (ode_modules/@vue/server-renderer/dist/server-renderer.cjs.js:111:17)
    at ssrRenderSlot (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:93:3)
    at _sfc_ssrRender$8 (bootstrap/ssr/ssr.js:199:3)
`

### Steps to reproduce:

You are able to reproduce this by directly following the  SSR instructions. [https://inertiajs.com/server-side-rendering](https://inertiajs.com/server-side-rendering)

"@inertiajs/vue3": "^1.0.15",
"inertiajs/inertia-laravel": "^1.0",
"laravel/framework": "^10.10",

I am seeing this on all Inertia repositories as I migrate them to SSR.

**Comment by iambryansanders** [comment]
FWIW - this works locally, but I get TypeErrors only on when I deploy with Laravel Forge.
