### ISSUE TITLE
Rendering bug in POST request - Laravel

### ISSUE THREAD

**Issue by Lochlite-Lochpay** [inertiajs/inertia#2160]
### Versions:

- `@inertiajs/vue3` version: ^1.0.14
        "php": "^8.2",
        "inertiajs/inertia-laravel": "^1.0",
        "laravel/framework": "^11.31",
        "@vitejs/plugin-vue": "^5.0.0",
        "@vue/server-renderer": "^3.3.13",
        "axios": "^1.7.4",
        "laravel-vite-plugin": "^1.0",
        "vite": "^6.0",
        "vue": "^3.3.13"

### Describe the problem:

The latest version of laravel is using the @inertiajs/vue3 package to build JetStream components (vue/inertia) as opposed to the previous @inertiajs/inertia-vue3 package, however, this has added a bug in the use of useFrom, because when sending the form and trying to get a new vue component as a response from the laravel controller, the error occurs: Uncaught (in promise) TypeError: this.resolveComponent is not a function at v.setPage (index-CMwq7I7n.js:22:24164) at index-CMwq7I7n.js:22:23003

**Objective**: An application has a registration system divided into 3 stages where each stage is a component. In order for the user to advance to the next stage, he must fill out a form and submit it to the server, which will respond by displaying the next stage.

### Steps to reproduce:
1. Create a laravel project with jetstream and inertiaJs following the documentation: https://jetstream.laravel.com/installation.html;

2. Create two routes
```
Route::get('/', [WelcomeController::class, 'index'])->name('welcome');
Route::post('/step-2', [WelcomeController::class, 'steptwo'])->name('welcome.steptwo');
```
3. Create a controller
```
<?php

namespace App\Http\Controllers;

use App\Models\Companies;
use Illuminate\Http\Request;
use Inertia\Inertia;

class WelcomeController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return Inertia::render('Welcome");
    } 

   public function steptwo(Request $request)
    {
        return Inertia::render('Steptwo", ['req' => $request->all()]);
    }
```
4. Create two components to be switched

Welcome.vue
```
<script setup>
import { useForm, usePage } from '@inertiajs/inertia-vue3'

const form = useForm({
    name: '',
    email: '',
});

const submit = () => {
    form.post(route('welcome.steptwo'));
};
</script>
<template>
     <form @submit.prevent="submit" class="w-full p-4 relative bg-white border border-gray-200 rounded-lg shadow">
            <div class="mb-3">
            <input v-model="form.name" type="text" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" placeholder="Full name" required>
            </div>
            <div class="mb-3">
            <input v-model="form.email" type="email" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" placeholder="user@mail.com" required>
            </div>
       <div class="flex items-center justify-between px-3 py-2 border-t dark:border-gray-600">
        <button type="submit" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
            Next
        </button>
    </div>
    </form>
</template>
```
Steptwo.vue
```
<script setup>
const props = defineProps({
    req: Object,
});

console.log(props.req);
</script>
<template>
<h1>You have reached the second stage!</h1>
</template>
```
5. Compile everything and start the test server. When you fill out the form and submit it you will see that the expected behavior of seeing the next component is frustrated, instead, all you have is an error in the console. This situation only occurs in the new package, in the previous one it works normally.

<hr/>

app.js
```
import './bootstrap';
import '../css/app.css';

import { createApp, h } from 'vue';
//import { createInertiaApp } from '@inertiajs/inertia-vue3';
import { createInertiaApp } from '@inertiajs/vue3';
import { resolvePageComponent } from 'laravel-vite-plugin/inertia-helpers';
import { ZiggyVue } from '../../vendor/tightenco/ziggy';

const appName = import.meta.env.VITE_APP_NAME || 'Laravel';

createInertiaApp({
    title: (title) => `${title} - ${appName}`,
    resolve: (name) => resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob('./Pages/**/*.vue')),
    setup({ el, App, props, plugin }) {
        return createApp({ render: () => h(App, props) })
            .use(plugin)
            .use(ZiggyVue)
            .mount(el);
    },
    progress: {
        color: '#4B5563',
    },
});
```

**Comment by Lochlite-Lochpay** [comment]
Apparently correcting the line to: import { useForm, usePage } from '@inertiajs/vue3' fixes the issue
