### ISSUE TITLE
Cannot read property 'component' of undefined

### ISSUE THREAD

**Issue by darkgoldblade01** [inertiajs/inertia#34]
Getting an error when loading the page in Chrome. Building succeeds though:

```
TypeError: Cannot read property 'component' of undefined
  at setPage(./node_modules/inertia/src/inertia.js:123:1)
  at init(./node_modules/inertia/src/inertia.js:20:1)
  at call(./node_modules/inertia-vue/src/app.js:25:12)
  at invokeWithErrorHandling(./node_modules/vue/dist/vue.runtime.esm.js:1854:1)
  at callHook(./node_modules/vue/dist/vue.runtime.esm.js:4213:1)
  at _init(./node_modules/vue/dist/vue.runtime.esm.js:5002:1)
  at new b(./node_modules/vue/dist/vue.runtime.esm.js:5148:1)
  at createComponentInstanceForVnode(./node_modules/vue/dist/vue.runtime.esm.js:3283:1)
  at i(./node_modules/vue/dist/vue.runtime.esm.js:3114:1)
  at createComponent(./node_modules/vue/dist/vue.runtime.esm.js:5972:1)
  at createElm(./node_modules/vue/dist/vue.runtime.esm.js:5919:1)
  at __patch__(./node_modules/vue/dist/vue.runtime.esm.js:6510:1)
  at _update(./node_modules/vue/dist/vue.runtime.esm.js:3939:1)
  at call(./node_modules/vue/dist/vue.runtime.esm.js:4060:1)
  at get(./node_modules/vue/dist/vue.runtime.esm.js:4473:1)
  at new dn(./node_modules/vue/dist/vue.runtime.esm.js:4462:1)
  at vm(./node_modules/vue/dist/vue.runtime.esm.js:4067:1)
  at $mount(./node_modules/vue/dist/vue.runtime.esm.js:8409:1)
  at call(./resources/js/app.js:99:4)
  at __webpack_require__(webpack/bootstrap:63:1)
  at call(./node_modules/moment/locale/x-pseudo.js:5:59)
  at __webpack_require__(webpack/bootstrap:63:1)
  at ? (webpack/bootstrap:195:1)
  at ? (webpack/bootstrap:195:1)
```

I also took a screenshot of what I am seeing in Sentry:

![2019-05-16-16-28-sentry io](https://user-images.githubusercontent.com/9066551/57893441-c5c28d80-77f7-11e9-997c-ff6b2f10032a.png)

**Comment by reinink** [comment]
It seems to be complaining about this line, which was changed today:

https://github.com/inertiajs/inertia/blob/b68adb34c1cfdfeb22daa0587fc7cadfeada7910/src/inertia.js#L123

Again, are you unable to confirm this locally? Is this _only_ happening in production? That is very confusing, and is going to be super hard for me to figure out. I'd love to have a repo that reproduces the issue.

**Comment by reinink** [comment]
Also, have you tried deleting the node_modules folder in production and reinstalling the assets?

**Comment by reinink** [comment]
Also, what version of node and npm are you running in prod, vs locally?

**Comment by darkgoldblade01** [comment]
I am only able to re-produce on the production. I am trying to node_modules deletion right now. I'll update once done. I am running 6.9.0 in both.

**Comment by darkgoldblade01** [comment]
Deleting and re-installing all packages (deleting `node_modules`, running `npm i`) fixed the issue. Strange though that it would cause an issue in the first place.

**Comment by darkgoldblade01** [comment]
I am going to close the issue, but bookmarking the page in case it every happens again (hopefully it doesn't!)

**Comment by reinink** [comment]
Yeah, that's dark. I'm not super surprised. We need to get these libraries on NPM and stop downloading them directly from GitHub. I bet that's part of the problem.

Glad you got it working though!

**Comment by darkgoldblade01** [comment]
Well, it was working...

**Comment by reinink** [comment]
Seriously??

**Comment by darkgoldblade01** [comment]
Yes, I have tried it personally with `yarn` on the server, rather than having forge do it. It causes an issue. Run NPM, and boom, it's fine.
